# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: false
  build-debug:
    cmds:
      - odin build . -out=bin/debug -debug
  debug:
    cmds:
      - odin build . -out=bin/debug -debug && ./bin/debug
  release:
    cmds:
      - odin build . -out=bin/release -min-link-libs -o:aggressive && ./bin/release
  check:
    cmds:
      - odin check .
     
