# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: false
  debug:
    cmds:
      - odin build . -out=bin/debug -debug
  check:
    cmds:
      - odin check .
     
